### ISSUE TITLE
too high fahrenheit readings with european version Froggit FT0073

### ISSUE THREAD

**Issue by hackgrid** [adilosa/weathermon#1]
Nevermind, just divide by ten to get the correct Fahrenheit value or read the comments of the original "Arduino-F007th-Sketches/Working sketch v3" to understand how to calculate the Celsius value correctly. Thanks :-)

**Comment by adilosa** [comment]
Since there's only one decimal place of precision anyway, temp values are left as integers until displayed to avoid floating point errors. :)

Also, the README has been updated with the temperature formulas, so people don't have to go searching anymore.
